/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4e33b4f3-b131-45d7-a38c-917233b77c14

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have formalized the paper's main results regarding the inradius of lemniscates of non-degenerate polynomials.
Specifically, we have proved:
1. Remark 3.2: Non-degenerate polynomials have simple roots (`remark_3_2_proof`).
2. Lemma 3.4: Existence of a root with small derivative (`lemma_3_4_proof`).
3. Theorem 2.1: The main bound on the inradius (`theorem_2_1_proof`).
4. Proposition 7.1: Reduction of the conjecture to the minimizer (`proposition_7_1_proof`).
5. Proposition 4.1: Verification for z^n - 1 (`proposition_4_1_proof`).

We also proved helper lemmas `psi_maps_to_lemniscate_proof` and `psi_deriv_at_zero_proof`.
The four classical results (Koebe 1/4, Fekete bound, Univalent branch existence, Minimizer existence) were axiomatized as requested.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 558fa151-3b39-4648-930c-f4bc2e293737

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of the paper "Inradius of Lemniscates for Non-Degenerate Polynomials".
We define the lemniscate, inradius, and non-degeneracy.
We define the statements of the four missing axioms: Koebe 1/4 Theorem, Fekete Bound, Univalent Branch Existence, and Minimizer Existence.
We prove Remark 3.2, Lemma 3.4, Theorem 2.1, Proposition 7.1, and Proposition 4.1, taking the necessary axioms as hypotheses.
Note: The axioms are formalized as definitions of their statements and passed as parameters to the theorems that require them, rather than being declared as top-level axioms, to ensure soundness and compatibility with the toolchain.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of the lemniscate of a polynomial P at level t.
-/
open Complex Polynomial Metric Set Filter Topology

noncomputable def lemniscate (P : Polynomial ℂ) (t : ℝ) : Set ℂ := {z | ‖P.eval z‖ < t}

/-
Definition of the inradius of a set Ω as the supremum of radii of balls contained in Ω.
-/
noncomputable def inradius (Ω : Set ℂ) : ℝ := sSup {r : ℝ | 0 < r ∧ ∃ z, Metric.ball z r ⊆ Ω}

/-
Definition of a non-degenerate polynomial: every critical value has modulus at least 1.
-/
def non_degenerate (P : Polynomial ℂ) : Prop :=
  ∀ ζ, deriv (fun z => P.eval z) ζ = 0 → 1 ≤ ‖P.eval ζ‖

/-
Definition of a univalent function on a set U: holomorphic and injective.
-/
def univalent (f : ℂ → ℂ) (U : Set ℂ) : Prop :=
  DifferentiableOn ℂ f U ∧ Set.InjOn f U

/-
Statement of the Koebe 1/4 Theorem.
-/
def KoebeQuarterStatement : Prop :=
  ∀ (f : ℂ → ℂ) (a b : ℂ), b ≠ 0 →
  DifferentiableOn ℂ f (Metric.ball 0 1) →
  Set.InjOn f (Metric.ball 0 1) →
  f 0 = a →
  deriv f 0 = b →
  Metric.ball a (‖b‖ / 4) ⊆ f '' (Metric.ball 0 1)

/-
Statement of the Fekete Bound: For n distinct points in the closed unit disc, the sum of log distances is bounded by (n/2) log n.
-/
def FeketeBoundStatement : Prop :=
  ∀ {n : ℕ} (z : Fin n → ℂ),
  Function.Injective z →
  (∀ i, ‖z i‖ ≤ 1) →
  ∑ i : Fin n, ∑ j : Fin n, (if i < j then Real.log ‖z i - z j‖ else 0) ≤ (n : ℝ) / 2 * Real.log n

/-
Statement of the Univalent Branch Existence Lemma.
-/
def UnivalentBranchExistenceStatement : Prop :=
  ∀ {n : ℕ} (P : Polynomial ℂ),
    P.Monic →
    P.natDegree = n →
    non_degenerate P →
    (∀ z ∈ P.roots, ‖z‖ ≤ 1) →
    P.roots.Nodup →
    ∀ z ∈ P.roots, ∃ ψ : ℂ → ℂ,
      DifferentiableOn ℂ ψ (Metric.ball 0 1) ∧
      (∀ w ∈ Metric.ball 0 1, P.eval (ψ w) = w) ∧
      ψ 0 = z ∧
      Set.InjOn ψ (Metric.ball 0 1)

/-
Definition of PolynomialsInDisc and MinimizerExistenceStatement.
-/
def PolynomialsInDisc (n : ℕ) : Set (Polynomial ℂ) :=
  {P | P.Monic ∧ P.natDegree = n ∧ ∀ z ∈ P.roots, ‖z‖ ≤ 1}

def MinimizerExistenceStatement : Prop :=
  ∀ n : ℕ, 1 ≤ n →
  ∃ P ∈ PolynomialsInDisc n,
    inradius (lemniscate P 1) = sInf {r | ∃ Q ∈ PolynomialsInDisc n, r = inradius (lemniscate Q 1)}

/-
Remark 3.2: Non-degenerate ⟹ all roots are simple.
-/
theorem remark_3_2 (P : Polynomial ℂ) (h_nd : non_degenerate P) : P.roots.Nodup := by
  -- Assume there's a duplicate root z. Then P(z) = 0 and P'(z) = 0.
  by_contra h_dup
  obtain ⟨z, hz⟩ : ∃ z, z ∈ P.roots ∧ P.derivative.eval z = 0 := by
    rw [ Multiset.nodup_iff_count_le_one ] at h_dup;
    obtain ⟨ z, hz ⟩ := not_forall.mp h_dup;
    norm_num +zetaDelta at *;
    exact ⟨ z, ⟨ by aesop_cat, by exact Polynomial.rootMultiplicity_pos ( by aesop_cat ) |>.1 <| pos_of_gt hz ⟩, by exact Polynomial.isRoot_iterate_derivative_of_lt_rootMultiplicity hz ⟩;
  exact absurd ( h_nd z ( by simpa [ Polynomial.derivative_eval ] using hz.2 ) ) ( by aesop )

/-
Lemma 3.4: There exists a root z of P such that |P'(z)| ≤ n.
-/
lemma lemma_3_4 (P : Polynomial ℂ) (n : ℕ) (h_monic : P.Monic) (h_deg : P.natDegree = n)
    (h_n : 1 ≤ n) (h_nd : non_degenerate P) (h_roots_disc : ∀ z ∈ P.roots, ‖z‖ ≤ 1)
    (h_fekete : FeketeBoundStatement) :
    ∃ z ∈ P.roots, ‖(derivative P).eval z‖ ≤ n := by
      -- Let $z_1, \dots, z_n$ be the roots of $P$.
      set roots := P.roots with h_roots
      have h_roots_card : Multiset.card roots = n := by
        -- By the Fundamental Theorem of Algebra, any non-constant polynomial over the complex numbers splits into linear factors.
        have h_splits : Polynomial.Splits (algebraMap ℂ ℂ) P := by
          exact?;
        erw [ Polynomial.splits_iff_card_roots ] at h_splits ; aesop
      obtain ⟨z, hz⟩ : ∃ z : Fin n → ℂ, Function.Injective z ∧ ∀ i : Fin n, P.eval (z i) = 0 := by
        -- Since $P$ is a monic polynomial of degree $n$, its roots form a multiset of cardinality $n$.
        obtain ⟨z_multiset, hz_multiset⟩ : ∃ z_multiset : Finset ℂ, z_multiset.card = n ∧ ∀ z ∈ z_multiset, P.eval z = 0 := by
          use P.roots.toFinset;
          rw [ ← h_roots_card, Multiset.toFinset_card_of_nodup ] ; aesop;
          exact?;
        obtain ⟨z_equiv, hz_equiv⟩ : ∃ z_equiv : Fin n ≃ z_multiset, True := by
          exact ⟨ Fintype.equivOfCardEq <| by aesop, trivial ⟩;
        exact ⟨ _, Subtype.coe_injective.comp z_equiv.injective, fun i => hz_multiset.2 _ <| z_equiv i |>.2 ⟩;
      -- By the properties of the derivative and roots, we know that $|P'(z_j)| = \prod_{i \neq j} |z_j - z_i|$.
      have h_deriv : ∀ j : Fin n, ‖(P.derivative.eval (z j))‖ = ∏ i ∈ Finset.univ.erase j, ‖(z j) - (z i)‖ := by
        -- By definition of $P$, we know that $P(z) = \prod_{i=1}^n (z - z_i)$.
        have hP_factor : P = Finset.prod Finset.univ fun i => (Polynomial.X - Polynomial.C (z i)) := by
          refine' Polynomial.eq_of_degree_sub_lt_of_eval_finset_eq _ _ _;
          exact Finset.image z Finset.univ;
          · convert Polynomial.degree_sub_lt _ _ _ <;> simp_all +decide [ Polynomial.degree_prod, Polynomial.degree_X_sub_C ];
            · rw [ Finset.card_image_of_injective _ hz.1, Finset.card_fin, Polynomial.degree_eq_natDegree ] <;> aesop;
            · rw [ Polynomial.degree_eq_natDegree ] <;> aesop;
            · aesop;
            · norm_num [ Polynomial.leadingCoeff_prod ];
          · simp_all +decide [ Polynomial.eval_prod, Finset.prod_eq_zero_iff, sub_eq_zero ];
            exact fun i => by rw [ Finset.prod_eq_zero ( Finset.mem_univ i ) ] ; ring;
        intro j; rw [ hP_factor ] ; simp +decide [ Polynomial.eval_prod, Finset.prod_eq_prod_diff_singleton_mul ( Finset.mem_univ j ) ] ;
        rw [ Finset.sdiff_singleton_eq_erase ];
      -- By the properties of logarithms and the Fekete bound, we have $\sum_{j=1}^n \log |P'(z_j)| \leq n \log n$.
      have h_log_deriv : ∑ j : Fin n, Real.log ‖(P.derivative.eval (z j))‖ ≤ n * Real.log n := by
        have h_log_deriv : ∑ j : Fin n, ∑ i ∈ Finset.univ.erase j, Real.log ‖(z j) - (z i)‖ ≤ n * Real.log n := by
          have h_log_deriv : ∑ j : Fin n, ∑ i ∈ Finset.univ.erase j, Real.log ‖(z j) - (z i)‖ = 2 * ∑ i : Fin n, ∑ j ∈ Finset.Ioi i, Real.log ‖(z i) - (z j)‖ := by
            clear h_deriv h_roots_card h_roots_disc h_roots h_deg h_monic h_nd h_fekete roots hz;
            induction h_n <;> simp_all +decide [ Fin.sum_univ_succ, Finset.sum_add_distrib ] ; ring!;
            simp +decide [ norm_sub_rev ] ; ring!;
          have := h_fekete ( fun i => z i ) ; simp_all +decide [ Finset.sum_ite, Finset.filter_lt_eq_Ioi ] ;
          linarith [ this fun i => h_roots_disc _ h_monic.ne_zero ( hz.2 i ) ];
        convert h_log_deriv using 2 ; rw [ h_deriv ] ; rw [ Real.log_prod _ _ fun i hi => norm_ne_zero_iff.mpr <| sub_ne_zero.mpr <| hz.1.ne <| by aesop ] ;
      contrapose! h_log_deriv;
      exact lt_of_le_of_lt ( by norm_num ) ( Finset.sum_lt_sum_of_nonempty ⟨ ⟨ 0, h_n ⟩, Finset.mem_univ _ ⟩ fun i hi => Real.log_lt_log ( by positivity ) ( h_log_deriv ( z i ) ( by aesop ) ) )

/-
Lemma: The univalent branch ψ maps the unit disc into the lemniscate {z : |P(z)| < 1}.
-/
lemma psi_maps_to_lemniscate (P : Polynomial ℂ) (ψ : ℂ → ℂ)
    (h_inv : ∀ w ∈ Metric.ball 0 1, P.eval (ψ w) = w) :
    ψ '' (Metric.ball 0 1) ⊆ lemniscate P 1 := by
      rintro _ ⟨ w, hw₁, rfl ⟩ ; unfold lemniscate; aesop;

/-
Lemma: The derivative of the univalent branch ψ at 0 is 1/P'(z).
-/
lemma psi_deriv_at_zero (P : Polynomial ℂ) (ψ : ℂ → ℂ) (z : ℂ)
    (h_inv : ∀ w ∈ Metric.ball 0 1, P.eval (ψ w) = w)
    (h_psi0 : ψ 0 = z)
    (h_diff : DifferentiableOn ℂ ψ (Metric.ball 0 1))
    (h_P_deriv_ne_zero : (derivative P).eval z ≠ 0) :
    deriv ψ 0 = ((derivative P).eval z)⁻¹ := by
      -- By the chain rule, we have that the derivative of $P(\psi(w))$ at $w = 0$ is $P'(\psi(0)) \cdot \psi'(0)$.
      have h_chain : deriv (fun w => P.eval (ψ w)) 0 = (Polynomial.derivative P).eval (ψ 0) * deriv ψ 0 := by
        convert HasDerivAt.deriv ( HasDerivAt.comp 0 ( P.hasDerivAt ( ψ 0 ) ) ( h_diff.hasDerivAt ( Metric.ball_mem_nhds _ one_pos ) ) ) using 1;
      rw [ inv_eq_of_mul_eq_one_right ] ; rw [ show deriv ( fun w => P.eval ( ψ w ) ) 0 = 1 by exact HasDerivAt.deriv ( HasDerivAt.congr_of_eventuallyEq ( hasDerivAt_id 0 ) <| Filter.eventuallyEq_of_mem ( Metric.ball_mem_nhds _ zero_lt_one ) fun x hx => h_inv x hx ) ] at h_chain ; aesop;

/-
Theorem 2.1: If P is a monic polynomial of degree n ≥ 1 with all roots in the closed unit disc, and P is non-degenerate, then the inradius of the lemniscate {z : |P(z)| < 1} is at least 1/(4n).
-/
theorem theorem_2_1 (P : Polynomial ℂ) (n : ℕ) (h_monic : P.Monic) (h_deg : P.natDegree = n)
    (h_n : 1 ≤ n) (h_nd : non_degenerate P) (h_roots_disc : ∀ z ∈ P.roots, ‖z‖ ≤ 1)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement) :
    inradius (lemniscate P 1) ≥ 1 / (4 * n) := by
      obtain ⟨z, hz⟩ : ∃ z ∈ P.roots, ‖(derivative P).eval z‖ ≤ n := lemma_3_4 P n h_monic h_deg h_n h_nd h_roots_disc h_fekete;
      obtain ⟨ ψ, hψ ⟩ := h_branch P h_monic h_deg h_nd h_roots_disc ( by
        exact? ) z hz.1
      generalize_proofs at *;
      -- By the properties of the derivative and the Koebe theorem, we have that the ball of radius $1/(4n)$ centered at $z$ is contained in the lemniscate.
      have h_ball : Metric.ball z (1 / (4 * n)) ⊆ lemniscate P 1 := by
        have h_psi_deriv : deriv ψ 0 = ((derivative P).eval z)⁻¹ := by
          apply psi_deriv_at_zero P ψ z hψ.2.1 hψ.2.2.1 hψ.1
          generalize_proofs at *; (
          intro H; have := h_nd z; simp_all +decide [ Polynomial.coeff_derivative ] ;
          norm_num at this)
        generalize_proofs at *;
        have := h_koebe ψ z ( ( Polynomial.eval z ( Polynomial.derivative P ) ) ⁻¹ ) ?_ ?_ ?_ ?_ <;> simp_all +decide [ div_eq_mul_inv ];
        · refine' Set.Subset.trans ( Metric.ball_subset_ball <| mul_le_mul_of_nonneg_right ( inv_anti₀ ( norm_pos_iff.mpr <| _ ) hz.2 ) <| by norm_num ) ( this.trans <| _ );
          · intro H; specialize h_nd z; simp_all +decide [ Polynomial.derivative_eval ] ;
            norm_num at h_nd;
          · exact psi_maps_to_lemniscate P ψ fun w hw => hψ.2.1 w <| by simpa using hw;
        · intro h; specialize h_nd z; simp_all +decide [ Polynomial.natDegree_eq_of_degree_eq_some ] ;
          norm_num at h_nd;
      refine' le_csSup _ _ <;> norm_num;
      · -- Since the lemniscate is bounded, there exists some $M > 0$ such that for all $z \in \mathbb{C}$, if $|P(z)| < 1$, then $|z| < M$.
        obtain ⟨M, hM⟩ : ∃ M > 0, ∀ z, ‖P.eval z‖ < 1 → ‖z‖ < M := by
          have h_bounded : Filter.Tendsto (fun z : ℂ => ‖P.eval z‖) (Filter.cocompact ℂ) Filter.atTop := by
            apply_rules [ Polynomial.tendsto_norm_atTop ];
            · exact Polynomial.natDegree_pos_iff_degree_pos.mp ( by linarith );
            · exact tendsto_norm_cocompact_atTop;
          have := h_bounded.eventually_gt_atTop 1;
          rw [ Filter.eventually_iff ] at this;
          rw [ Filter.mem_cocompact ] at this;
          obtain ⟨ t, ht₁, ht₂ ⟩ := this; rcases ht₁.isBounded.exists_pos_norm_le with ⟨ M, hM ⟩ ; exact ⟨ M + 1, by linarith [ hM.1 ], fun z hz => lt_of_le_of_lt ( hM.2 z <| by exact Classical.not_not.1 fun h => not_lt_of_ge ( le_of_lt <| ht₂ h ) hz ) <| by linarith ⟩ ;
        use M + 1;
        rintro r ⟨ hr₀, z, hz ⟩;
        contrapose! hM;
        intro hM_pos
        obtain ⟨w, hw⟩ : ∃ w ∈ Metric.ball z r, ‖w‖ ≥ M := by
          by_cases hz_zero : z = 0;
          · exact ⟨ M, by simpa [ hz_zero, abs_of_pos hM_pos ] using by linarith, by simpa [ hz_zero, abs_of_pos hM_pos ] ⟩;
          · refine' ⟨ z + ( r - 1 ) * ( z / ‖z‖ ), _, _ ⟩ <;> norm_num [ hz_zero ];
            · norm_cast;
              rw [ Real.norm_of_nonneg ] <;> linarith;
            · rw [ show z + ( r - 1 ) * ( z / ‖z‖ ) = ( 1 + ( r - 1 ) / ‖z‖ ) * z by ring, norm_mul ];
              norm_cast ; norm_num [ hz_zero ];
              rw [ abs_of_nonneg ] <;> nlinarith [ norm_pos_iff.mpr hz_zero, div_mul_cancel₀ ( r - 1 ) ( norm_ne_zero_iff.mpr hz_zero ) ];
        exact ⟨ w, hz hw.1, hw.2 ⟩;
      · exact ⟨ h_n, z, by simpa [ mul_comm ] using h_ball ⟩

/-
Definition of rho_n as the infimum of inradii of lemniscates of polynomials in PolynomialsInDisc n.
-/
noncomputable def rho_n (n : ℕ) : ℝ := sInf {r | ∃ P ∈ PolynomialsInDisc n, r = inradius (lemniscate P 1)}

/-
Proposition 7.1: If the inradius minimizer over all such polynomials is non-degenerate, then ρₙ ≥ 1/(4n).
-/
theorem proposition_7_1 (n : ℕ) (h_n : 1 ≤ n)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement)
    (P : Polynomial ℂ) (hP : P ∈ PolynomialsInDisc n)
    (h_min : inradius (lemniscate P 1) = rho_n n)
    (h_nd : non_degenerate P) :
    rho_n n ≥ 1 / (4 * n) := by
      convert theorem_2_1 P n hP.1 hP.2.1 h_n h_nd ( hP.2.2 ) h_koebe h_fekete h_branch using 1 ; aesop;

/-
Proposition 4.1: The polynomial zⁿ - 1 is non-degenerate, and our bound gives inrad ≥ 1/(4n).
-/
theorem proposition_4_1 (n : ℕ) (h_n : 1 ≤ n)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement) :
    let P := (Polynomial.X : Polynomial ℂ) ^ n - 1
    non_degenerate P ∧ inradius (lemniscate P 1) ≥ 1 / (4 * n) := by
      refine' ⟨ _, _ ⟩;
      · intro ζ hζ; rcases n with ( _ | _ | n ) <;> simp_all +decide [ sub_eq_iff_eq_add ] ;
        norm_cast at hζ ; aesop;
      · convert theorem_2_1 _ n _ _ _ _ _ _ _ _ using 1 <;> norm_num;
        any_goals assumption;
        · exact Polynomial.monic_X_pow_sub_C _ ( by linarith );
        · erw [ Polynomial.natDegree_X_pow_sub_C ];
        · intro ζ hζ; rcases n with ( _ | _ | n ) <;> simp_all +decide [ sub_eq_iff_eq_add ] ;
          norm_cast at hζ ; aesop;
        · exact fun z _ hz => by have := congr_arg Norm.norm ( eq_of_sub_eq_zero hz ) ; norm_num at this ; rw [ pow_eq_one_iff_of_nonneg ] at this <;> aesop;

/-
If a polynomial P is non-degenerate (all critical values have norm >= 1), then all its roots are simple (no duplicate roots).
-/
theorem remark_3_2_proof (P : Polynomial ℂ) (h_nd : non_degenerate P) : P.roots.Nodup := by
  exact?

/-
There exists a root z of P such that |P'(z)| ≤ n.
-/
lemma lemma_3_4_proof (P : Polynomial ℂ) (n : ℕ) (h_monic : P.Monic) (h_deg : P.natDegree = n)
    (h_n : 1 ≤ n) (h_nd : non_degenerate P) (h_roots_disc : ∀ z ∈ P.roots, ‖z‖ ≤ 1)
    (h_fekete : FeketeBoundStatement) :
    ∃ z ∈ P.roots, ‖(derivative P).eval z‖ ≤ n := by
      convert lemma_3_4 P n h_monic h_deg h_n h_nd h_roots_disc h_fekete using 1

/-
The univalent branch ψ maps the unit disc into the lemniscate {z : |P(z)| < 1}.
-/
lemma psi_maps_to_lemniscate_proof (P : Polynomial ℂ) (ψ : ℂ → ℂ)
    (h_inv : ∀ w ∈ Metric.ball 0 1, P.eval (ψ w) = w) :
    ψ '' (Metric.ball 0 1) ⊆ lemniscate P 1 := by
      exact?

/-
The derivative of the univalent branch ψ at 0 is 1/P'(z).
-/
lemma psi_deriv_at_zero_proof (P : Polynomial ℂ) (ψ : ℂ → ℂ) (z : ℂ)
    (h_inv : ∀ w ∈ Metric.ball 0 1, P.eval (ψ w) = w)
    (h_psi0 : ψ 0 = z)
    (h_diff : DifferentiableOn ℂ ψ (Metric.ball 0 1))
    (h_P_deriv_ne_zero : (derivative P).eval z ≠ 0) :
    deriv ψ 0 = ((derivative P).eval z)⁻¹ := by
      exact?

/-
If P is a monic polynomial of degree n ≥ 1 with all roots in the closed unit disc, and P is non-degenerate, then the inradius of the lemniscate {z : |P(z)| < 1} is at least 1/(4n).
-/
theorem theorem_2_1_proof (P : Polynomial ℂ) (n : ℕ) (h_monic : P.Monic) (h_deg : P.natDegree = n)
    (h_n : 1 ≤ n) (h_nd : non_degenerate P) (h_roots_disc : ∀ z ∈ P.roots, ‖z‖ ≤ 1)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement) :
    inradius (lemniscate P 1) ≥ 1 / (4 * n) := by
      apply_rules [ theorem_2_1 ]

/-
If the inradius minimizer over all such polynomials is non-degenerate, then ρₙ ≥ 1/(4n).
-/
theorem proposition_7_1_proof (n : ℕ) (h_n : 1 ≤ n)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement)
    (P : Polynomial ℂ) (hP : P ∈ PolynomialsInDisc n)
    (h_min : inradius (lemniscate P 1) = rho_n n)
    (h_nd : non_degenerate P) :
    rho_n n ≥ 1 / (4 * n) := by
      convert theorem_2_1 P n hP.1 hP.2.1 h_n h_nd ( hP.2.2 ) h_koebe h_fekete h_branch using 1 ; aesop;

/-
The polynomial zⁿ - 1 is non-degenerate, and our bound gives inrad ≥ 1/(4n).
-/
theorem proposition_4_1_proof (n : ℕ) (h_n : 1 ≤ n)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement) :
    let P := (Polynomial.X : Polynomial ℂ) ^ n - 1
    non_degenerate P ∧ inradius (lemniscate P 1) ≥ 1 / (4 * n) := by
      convert proposition_4_1 n h_n h_koebe h_fekete h_branch using 1
