/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d03629df-0f87-4f0b-a0ac-9a4bf7791eb6

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of the paper 'Inradius of Lemniscates'.
This file extends the existing formalization with proofs of the Fekete bound from Hadamard's inequality,
the Dual Fekete bound, the conformal factorization bound, and key lemmas including the Petals lemma (axiomatized),
Lemma 5.2 (second derivative chain rule), Corollary 5.3, and the Blaschke product identity.
It includes the definitions of the new axioms and the proofs of the new results as requested.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4e33b4f3-b131-45d7-a38c-917233b77c14

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have formalized the paper's main results regarding the inradius of lemniscates of non-degenerate polynomials.
Specifically, we have proved:
1. Remark 3.2: Non-degenerate polynomials have simple roots (`remark_3_2_proof`).
2. Lemma 3.4: Existence of a root with small derivative (`lemma_3_4_proof`).
3. Theorem 2.1: The main bound on the inradius (`theorem_2_1_proof`).
4. Proposition 7.1: Reduction of the conjecture to the minimizer (`proposition_7_1_proof`).
5. Proposition 4.1: Verification for z^n - 1 (`proposition_4_1_proof`).

We also proved helper lemmas `psi_maps_to_lemniscate_proof` and `psi_deriv_at_zero_proof`.
The four classical results (Koebe 1/4, Fekete bound, Univalent branch existence, Minimizer existence) were axiomatized as requested.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 558fa151-3b39-4648-930c-f4bc2e293737

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of the paper "Inradius of Lemniscates for Non-Degenerate Polynomials".
We define the lemniscate, inradius, and non-degeneracy.
We define the statements of the four missing axioms: Koebe 1/4 Theorem, Fekete Bound, Univalent Branch Existence, and Minimizer Existence.
We prove Remark 3.2, Lemma 3.4, Theorem 2.1, Proposition 7.1, and Proposition 4.1, taking the necessary axioms as hypotheses.
Note: The axioms are formalized as definitions of their statements and passed as parameters to the theorems that require them, rather than being declared as top-level axioms, to ensure soundness and compatibility with the toolchain.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of the lemniscate of a polynomial P at level t.
-/
open Complex Polynomial Metric Set Filter Topology

noncomputable def lemniscate (P : Polynomial ℂ) (t : ℝ) : Set ℂ := {z | ‖P.eval z‖ < t}

/-
Definition of the inradius of a set Ω as the supremum of radii of balls contained in Ω.
-/
noncomputable def inradius (Ω : Set ℂ) : ℝ := sSup {r : ℝ | 0 < r ∧ ∃ z, Metric.ball z r ⊆ Ω}

/-
Definition of a non-degenerate polynomial: every critical value has modulus at least 1.
-/
def non_degenerate (P : Polynomial ℂ) : Prop :=
  ∀ ζ, deriv (fun z => P.eval z) ζ = 0 → 1 ≤ ‖P.eval ζ‖

/-
Definition of a univalent function on a set U: holomorphic and injective.
-/
def univalent (f : ℂ → ℂ) (U : Set ℂ) : Prop :=
  DifferentiableOn ℂ f U ∧ Set.InjOn f U

/-
Statement of the Koebe 1/4 Theorem.
-/
def KoebeQuarterStatement : Prop :=
  ∀ (f : ℂ → ℂ) (a b : ℂ), b ≠ 0 →
  DifferentiableOn ℂ f (Metric.ball 0 1) →
  Set.InjOn f (Metric.ball 0 1) →
  f 0 = a →
  deriv f 0 = b →
  Metric.ball a (‖b‖ / 4) ⊆ f '' (Metric.ball 0 1)

/-
Statement of the Fekete Bound: For n distinct points in the closed unit disc, the sum of log distances is bounded by (n/2) log n.
-/
def FeketeBoundStatement : Prop :=
  ∀ {n : ℕ} (z : Fin n → ℂ),
  Function.Injective z →
  (∀ i, ‖z i‖ ≤ 1) →
  ∑ i : Fin n, ∑ j : Fin n, (if i < j then Real.log ‖z i - z j‖ else 0) ≤ (n : ℝ) / 2 * Real.log n

/-
Statement of the Univalent Branch Existence Lemma.
-/
def UnivalentBranchExistenceStatement : Prop :=
  ∀ {n : ℕ} (P : Polynomial ℂ),
    P.Monic →
    P.natDegree = n →
    non_degenerate P →
    (∀ z ∈ P.roots, ‖z‖ ≤ 1) →
    P.roots.Nodup →
    ∀ z ∈ P.roots, ∃ ψ : ℂ → ℂ,
      DifferentiableOn ℂ ψ (Metric.ball 0 1) ∧
      (∀ w ∈ Metric.ball 0 1, P.eval (ψ w) = w) ∧
      ψ 0 = z ∧
      Set.InjOn ψ (Metric.ball 0 1)

/-
Definition of PolynomialsInDisc and MinimizerExistenceStatement.
-/
def PolynomialsInDisc (n : ℕ) : Set (Polynomial ℂ) :=
  {P | P.Monic ∧ P.natDegree = n ∧ ∀ z ∈ P.roots, ‖z‖ ≤ 1}

def MinimizerExistenceStatement : Prop :=
  ∀ n : ℕ, 1 ≤ n →
  ∃ P ∈ PolynomialsInDisc n,
    inradius (lemniscate P 1) = sInf {r | ∃ Q ∈ PolynomialsInDisc n, r = inradius (lemniscate Q 1)}

/-
Remark 3.2: Non-degenerate ⟹ all roots are simple.
-/
theorem remark_3_2 (P : Polynomial ℂ) (h_nd : non_degenerate P) : P.roots.Nodup := by
  -- Assume there's a duplicate root z. Then P(z) = 0 and P'(z) = 0.
  by_contra h_dup
  obtain ⟨z, hz⟩ : ∃ z, z ∈ P.roots ∧ P.derivative.eval z = 0 := by
    rw [ Multiset.nodup_iff_count_le_one ] at h_dup;
    obtain ⟨ z, hz ⟩ := not_forall.mp h_dup;
    norm_num +zetaDelta at *;
    exact ⟨ z, ⟨ by aesop_cat, by exact Polynomial.rootMultiplicity_pos ( by aesop_cat ) |>.1 <| pos_of_gt hz ⟩, by exact Polynomial.isRoot_iterate_derivative_of_lt_rootMultiplicity hz ⟩;
  exact absurd ( h_nd z ( by simpa [ Polynomial.derivative_eval ] using hz.2 ) ) ( by aesop )

/-
Lemma 3.4: There exists a root z of P such that |P'(z)| ≤ n.
-/
lemma lemma_3_4 (P : Polynomial ℂ) (n : ℕ) (h_monic : P.Monic) (h_deg : P.natDegree = n)
    (h_n : 1 ≤ n) (h_nd : non_degenerate P) (h_roots_disc : ∀ z ∈ P.roots, ‖z‖ ≤ 1)
    (h_fekete : FeketeBoundStatement) :
    ∃ z ∈ P.roots, ‖(derivative P).eval z‖ ≤ n := by
      -- Let $z_1, \dots, z_n$ be the roots of $P$.
      set roots := P.roots with h_roots
      have h_roots_card : Multiset.card roots = n := by
        -- By the Fundamental Theorem of Algebra, any non-constant polynomial over the complex numbers splits into linear factors.
        have h_splits : Polynomial.Splits (algebraMap ℂ ℂ) P := by
          exact?;
        erw [ Polynomial.splits_iff_card_roots ] at h_splits ; aesop
      obtain ⟨z, hz⟩ : ∃ z : Fin n → ℂ, Function.Injective z ∧ ∀ i : Fin n, P.eval (z i) = 0 := by
        -- Since $P$ is a monic polynomial of degree $n$, its roots form a multiset of cardinality $n$.
        obtain ⟨z_multiset, hz_multiset⟩ : ∃ z_multiset : Finset ℂ, z_multiset.card = n ∧ ∀ z ∈ z_multiset, P.eval z = 0 := by
          use P.roots.toFinset;
          rw [ ← h_roots_card, Multiset.toFinset_card_of_nodup ] ; aesop;
          exact?;
        obtain ⟨z_equiv, hz_equiv⟩ : ∃ z_equiv : Fin n ≃ z_multiset, True := by
          exact ⟨ Fintype.equivOfCardEq <| by aesop, trivial ⟩;
        exact ⟨ _, Subtype.coe_injective.comp z_equiv.injective, fun i => hz_multiset.2 _ <| z_equiv i |>.2 ⟩;
      -- By the properties of the derivative and roots, we know that $|P'(z_j)| = \prod_{i \neq j} |z_j - z_i|$.
      have h_deriv : ∀ j : Fin n, ‖(P.derivative.eval (z j))‖ = ∏ i ∈ Finset.univ.erase j, ‖(z j) - (z i)‖ := by
        -- By definition of $P$, we know that $P(z) = \prod_{i=1}^n (z - z_i)$.
        have hP_factor : P = Finset.prod Finset.univ fun i => (Polynomial.X - Polynomial.C (z i)) := by
          refine' Polynomial.eq_of_degree_sub_lt_of_eval_finset_eq _ _ _;
          exact Finset.image z Finset.univ;
          · convert Polynomial.degree_sub_lt _ _ _ <;> simp_all +decide [ Polynomial.degree_prod, Polynomial.degree_X_sub_C ];
            · rw [ Finset.card_image_of_injective _ hz.1, Finset.card_fin, Polynomial.degree_eq_natDegree ] <;> aesop;
            · rw [ Polynomial.degree_eq_natDegree ] <;> aesop;
            · aesop;
            · norm_num [ Polynomial.leadingCoeff_prod ];
          · simp_all +decide [ Polynomial.eval_prod, Finset.prod_eq_zero_iff, sub_eq_zero ];
            exact fun i => by rw [ Finset.prod_eq_zero ( Finset.mem_univ i ) ] ; ring;
        intro j; rw [ hP_factor ] ; simp +decide [ Polynomial.eval_prod, Finset.prod_eq_prod_diff_singleton_mul ( Finset.mem_univ j ) ] ;
        rw [ Finset.sdiff_singleton_eq_erase ];
      -- By the properties of logarithms and the Fekete bound, we have $\sum_{j=1}^n \log |P'(z_j)| \leq n \log n$.
      have h_log_deriv : ∑ j : Fin n, Real.log ‖(P.derivative.eval (z j))‖ ≤ n * Real.log n := by
        have h_log_deriv : ∑ j : Fin n, ∑ i ∈ Finset.univ.erase j, Real.log ‖(z j) - (z i)‖ ≤ n * Real.log n := by
          have h_log_deriv : ∑ j : Fin n, ∑ i ∈ Finset.univ.erase j, Real.log ‖(z j) - (z i)‖ = 2 * ∑ i : Fin n, ∑ j ∈ Finset.Ioi i, Real.log ‖(z i) - (z j)‖ := by
            clear h_deriv h_roots_card h_roots_disc h_roots h_deg h_monic h_nd h_fekete roots hz;
            induction h_n <;> simp_all +decide [ Fin.sum_univ_succ, Finset.sum_add_distrib ] ; ring!;
            simp +decide [ norm_sub_rev ] ; ring!;
          have := h_fekete ( fun i => z i ) ; simp_all +decide [ Finset.sum_ite, Finset.filter_lt_eq_Ioi ] ;
          linarith [ this fun i => h_roots_disc _ h_monic.ne_zero ( hz.2 i ) ];
        convert h_log_deriv using 2 ; rw [ h_deriv ] ; rw [ Real.log_prod _ _ fun i hi => norm_ne_zero_iff.mpr <| sub_ne_zero.mpr <| hz.1.ne <| by aesop ] ;
      contrapose! h_log_deriv;
      exact lt_of_le_of_lt ( by norm_num ) ( Finset.sum_lt_sum_of_nonempty ⟨ ⟨ 0, h_n ⟩, Finset.mem_univ _ ⟩ fun i hi => Real.log_lt_log ( by positivity ) ( h_log_deriv ( z i ) ( by aesop ) ) )

/-
Lemma: The univalent branch ψ maps the unit disc into the lemniscate {z : |P(z)| < 1}.
-/
lemma psi_maps_to_lemniscate (P : Polynomial ℂ) (ψ : ℂ → ℂ)
    (h_inv : ∀ w ∈ Metric.ball 0 1, P.eval (ψ w) = w) :
    ψ '' (Metric.ball 0 1) ⊆ lemniscate P 1 := by
      rintro _ ⟨ w, hw₁, rfl ⟩ ; unfold lemniscate; aesop;

/-
Lemma: The derivative of the univalent branch ψ at 0 is 1/P'(z).
-/
lemma psi_deriv_at_zero (P : Polynomial ℂ) (ψ : ℂ → ℂ) (z : ℂ)
    (h_inv : ∀ w ∈ Metric.ball 0 1, P.eval (ψ w) = w)
    (h_psi0 : ψ 0 = z)
    (h_diff : DifferentiableOn ℂ ψ (Metric.ball 0 1))
    (h_P_deriv_ne_zero : (derivative P).eval z ≠ 0) :
    deriv ψ 0 = ((derivative P).eval z)⁻¹ := by
      -- By the chain rule, we have that the derivative of $P(\psi(w))$ at $w = 0$ is $P'(\psi(0)) \cdot \psi'(0)$.
      have h_chain : deriv (fun w => P.eval (ψ w)) 0 = (Polynomial.derivative P).eval (ψ 0) * deriv ψ 0 := by
        convert HasDerivAt.deriv ( HasDerivAt.comp 0 ( P.hasDerivAt ( ψ 0 ) ) ( h_diff.hasDerivAt ( Metric.ball_mem_nhds _ one_pos ) ) ) using 1;
      rw [ inv_eq_of_mul_eq_one_right ] ; rw [ show deriv ( fun w => P.eval ( ψ w ) ) 0 = 1 by exact HasDerivAt.deriv ( HasDerivAt.congr_of_eventuallyEq ( hasDerivAt_id 0 ) <| Filter.eventuallyEq_of_mem ( Metric.ball_mem_nhds _ zero_lt_one ) fun x hx => h_inv x hx ) ] at h_chain ; aesop;

/-
Theorem 2.1: If P is a monic polynomial of degree n ≥ 1 with all roots in the closed unit disc, and P is non-degenerate, then the inradius of the lemniscate {z : |P(z)| < 1} is at least 1/(4n).
-/
theorem theorem_2_1 (P : Polynomial ℂ) (n : ℕ) (h_monic : P.Monic) (h_deg : P.natDegree = n)
    (h_n : 1 ≤ n) (h_nd : non_degenerate P) (h_roots_disc : ∀ z ∈ P.roots, ‖z‖ ≤ 1)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement) :
    inradius (lemniscate P 1) ≥ 1 / (4 * n) := by
      obtain ⟨z, hz⟩ : ∃ z ∈ P.roots, ‖(derivative P).eval z‖ ≤ n := lemma_3_4 P n h_monic h_deg h_n h_nd h_roots_disc h_fekete;
      obtain ⟨ ψ, hψ ⟩ := h_branch P h_monic h_deg h_nd h_roots_disc ( by
        exact? ) z hz.1
      generalize_proofs at *;
      -- By the properties of the derivative and the Koebe theorem, we have that the ball of radius $1/(4n)$ centered at $z$ is contained in the lemniscate.
      have h_ball : Metric.ball z (1 / (4 * n)) ⊆ lemniscate P 1 := by
        have h_psi_deriv : deriv ψ 0 = ((derivative P).eval z)⁻¹ := by
          apply psi_deriv_at_zero P ψ z hψ.2.1 hψ.2.2.1 hψ.1
          generalize_proofs at *; (
          intro H; have := h_nd z; simp_all +decide [ Polynomial.coeff_derivative ] ;
          norm_num at this)
        generalize_proofs at *;
        have := h_koebe ψ z ( ( Polynomial.eval z ( Polynomial.derivative P ) ) ⁻¹ ) ?_ ?_ ?_ ?_ <;> simp_all +decide [ div_eq_mul_inv ];
        · refine' Set.Subset.trans ( Metric.ball_subset_ball <| mul_le_mul_of_nonneg_right ( inv_anti₀ ( norm_pos_iff.mpr <| _ ) hz.2 ) <| by norm_num ) ( this.trans <| _ );
          · intro H; specialize h_nd z; simp_all +decide [ Polynomial.derivative_eval ] ;
            norm_num at h_nd;
          · exact psi_maps_to_lemniscate P ψ fun w hw => hψ.2.1 w <| by simpa using hw;
        · intro h; specialize h_nd z; simp_all +decide [ Polynomial.natDegree_eq_of_degree_eq_some ] ;
          norm_num at h_nd;
      refine' le_csSup _ _ <;> norm_num;
      · -- Since the lemniscate is bounded, there exists some $M > 0$ such that for all $z \in \mathbb{C}$, if $|P(z)| < 1$, then $|z| < M$.
        obtain ⟨M, hM⟩ : ∃ M > 0, ∀ z, ‖P.eval z‖ < 1 → ‖z‖ < M := by
          have h_bounded : Filter.Tendsto (fun z : ℂ => ‖P.eval z‖) (Filter.cocompact ℂ) Filter.atTop := by
            apply_rules [ Polynomial.tendsto_norm_atTop ];
            · exact Polynomial.natDegree_pos_iff_degree_pos.mp ( by linarith );
            · exact tendsto_norm_cocompact_atTop;
          have := h_bounded.eventually_gt_atTop 1;
          rw [ Filter.eventually_iff ] at this;
          rw [ Filter.mem_cocompact ] at this;
          obtain ⟨ t, ht₁, ht₂ ⟩ := this; rcases ht₁.isBounded.exists_pos_norm_le with ⟨ M, hM ⟩ ; exact ⟨ M + 1, by linarith [ hM.1 ], fun z hz => lt_of_le_of_lt ( hM.2 z <| by exact Classical.not_not.1 fun h => not_lt_of_ge ( le_of_lt <| ht₂ h ) hz ) <| by linarith ⟩ ;
        use M + 1;
        rintro r ⟨ hr₀, z, hz ⟩;
        contrapose! hM;
        intro hM_pos
        obtain ⟨w, hw⟩ : ∃ w ∈ Metric.ball z r, ‖w‖ ≥ M := by
          by_cases hz_zero : z = 0;
          · exact ⟨ M, by simpa [ hz_zero, abs_of_pos hM_pos ] using by linarith, by simpa [ hz_zero, abs_of_pos hM_pos ] ⟩;
          · refine' ⟨ z + ( r - 1 ) * ( z / ‖z‖ ), _, _ ⟩ <;> norm_num [ hz_zero ];
            · norm_cast;
              rw [ Real.norm_of_nonneg ] <;> linarith;
            · rw [ show z + ( r - 1 ) * ( z / ‖z‖ ) = ( 1 + ( r - 1 ) / ‖z‖ ) * z by ring, norm_mul ];
              norm_cast ; norm_num [ hz_zero ];
              rw [ abs_of_nonneg ] <;> nlinarith [ norm_pos_iff.mpr hz_zero, div_mul_cancel₀ ( r - 1 ) ( norm_ne_zero_iff.mpr hz_zero ) ];
        exact ⟨ w, hz hw.1, hw.2 ⟩;
      · exact ⟨ h_n, z, by simpa [ mul_comm ] using h_ball ⟩

/-
Definition of rho_n as the infimum of inradii of lemniscates of polynomials in PolynomialsInDisc n.
-/
noncomputable def rho_n (n : ℕ) : ℝ := sInf {r | ∃ P ∈ PolynomialsInDisc n, r = inradius (lemniscate P 1)}

/-
Proposition 7.1: If the inradius minimizer over all such polynomials is non-degenerate, then ρₙ ≥ 1/(4n).
-/
theorem proposition_7_1 (n : ℕ) (h_n : 1 ≤ n)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement)
    (P : Polynomial ℂ) (hP : P ∈ PolynomialsInDisc n)
    (h_min : inradius (lemniscate P 1) = rho_n n)
    (h_nd : non_degenerate P) :
    rho_n n ≥ 1 / (4 * n) := by
      convert theorem_2_1 P n hP.1 hP.2.1 h_n h_nd ( hP.2.2 ) h_koebe h_fekete h_branch using 1 ; aesop;

/-
Proposition 4.1: The polynomial zⁿ - 1 is non-degenerate, and our bound gives inrad ≥ 1/(4n).
-/
theorem proposition_4_1 (n : ℕ) (h_n : 1 ≤ n)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement) :
    let P := (Polynomial.X : Polynomial ℂ) ^ n - 1
    non_degenerate P ∧ inradius (lemniscate P 1) ≥ 1 / (4 * n) := by
      refine' ⟨ _, _ ⟩;
      · intro ζ hζ; rcases n with ( _ | _ | n ) <;> simp_all +decide [ sub_eq_iff_eq_add ] ;
        norm_cast at hζ ; aesop;
      · convert theorem_2_1 _ n _ _ _ _ _ _ _ _ using 1 <;> norm_num;
        any_goals assumption;
        · exact Polynomial.monic_X_pow_sub_C _ ( by linarith );
        · erw [ Polynomial.natDegree_X_pow_sub_C ];
        · intro ζ hζ; rcases n with ( _ | _ | n ) <;> simp_all +decide [ sub_eq_iff_eq_add ] ;
          norm_cast at hζ ; aesop;
        · exact fun z _ hz => by have := congr_arg Norm.norm ( eq_of_sub_eq_zero hz ) ; norm_num at this ; rw [ pow_eq_one_iff_of_nonneg ] at this <;> aesop;

/-
If a polynomial P is non-degenerate (all critical values have norm >= 1), then all its roots are simple (no duplicate roots).
-/
theorem remark_3_2_proof (P : Polynomial ℂ) (h_nd : non_degenerate P) : P.roots.Nodup := by
  exact?

/-
There exists a root z of P such that |P'(z)| ≤ n.
-/
lemma lemma_3_4_proof (P : Polynomial ℂ) (n : ℕ) (h_monic : P.Monic) (h_deg : P.natDegree = n)
    (h_n : 1 ≤ n) (h_nd : non_degenerate P) (h_roots_disc : ∀ z ∈ P.roots, ‖z‖ ≤ 1)
    (h_fekete : FeketeBoundStatement) :
    ∃ z ∈ P.roots, ‖(derivative P).eval z‖ ≤ n := by
      convert lemma_3_4 P n h_monic h_deg h_n h_nd h_roots_disc h_fekete using 1

/-
The univalent branch ψ maps the unit disc into the lemniscate {z : |P(z)| < 1}.
-/
lemma psi_maps_to_lemniscate_proof (P : Polynomial ℂ) (ψ : ℂ → ℂ)
    (h_inv : ∀ w ∈ Metric.ball 0 1, P.eval (ψ w) = w) :
    ψ '' (Metric.ball 0 1) ⊆ lemniscate P 1 := by
      exact?

/-
The derivative of the univalent branch ψ at 0 is 1/P'(z).
-/
lemma psi_deriv_at_zero_proof (P : Polynomial ℂ) (ψ : ℂ → ℂ) (z : ℂ)
    (h_inv : ∀ w ∈ Metric.ball 0 1, P.eval (ψ w) = w)
    (h_psi0 : ψ 0 = z)
    (h_diff : DifferentiableOn ℂ ψ (Metric.ball 0 1))
    (h_P_deriv_ne_zero : (derivative P).eval z ≠ 0) :
    deriv ψ 0 = ((derivative P).eval z)⁻¹ := by
      exact?

/-
If P is a monic polynomial of degree n ≥ 1 with all roots in the closed unit disc, and P is non-degenerate, then the inradius of the lemniscate {z : |P(z)| < 1} is at least 1/(4n).
-/
theorem theorem_2_1_proof (P : Polynomial ℂ) (n : ℕ) (h_monic : P.Monic) (h_deg : P.natDegree = n)
    (h_n : 1 ≤ n) (h_nd : non_degenerate P) (h_roots_disc : ∀ z ∈ P.roots, ‖z‖ ≤ 1)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement) :
    inradius (lemniscate P 1) ≥ 1 / (4 * n) := by
      apply_rules [ theorem_2_1 ]

/-
If the inradius minimizer over all such polynomials is non-degenerate, then ρₙ ≥ 1/(4n).
-/
theorem proposition_7_1_proof (n : ℕ) (h_n : 1 ≤ n)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement)
    (P : Polynomial ℂ) (hP : P ∈ PolynomialsInDisc n)
    (h_min : inradius (lemniscate P 1) = rho_n n)
    (h_nd : non_degenerate P) :
    rho_n n ≥ 1 / (4 * n) := by
      convert theorem_2_1 P n hP.1 hP.2.1 h_n h_nd ( hP.2.2 ) h_koebe h_fekete h_branch using 1 ; aesop;

/-
The polynomial zⁿ - 1 is non-degenerate, and our bound gives inrad ≥ 1/(4n).
-/
theorem proposition_4_1_proof (n : ℕ) (h_n : 1 ≤ n)
    (h_koebe : KoebeQuarterStatement) (h_fekete : FeketeBoundStatement)
    (h_branch : UnivalentBranchExistenceStatement) :
    let P := (Polynomial.X : Polynomial ℂ) ^ n - 1
    non_degenerate P ∧ inradius (lemniscate P 1) ≥ 1 / (4 * n) := by
      convert proposition_4_1 n h_n h_koebe h_fekete h_branch using 1


/-
Definitions of the new axioms: Hadamard's Inequality, Petals Statement (Lemma 5.1), and Conformal Factorization (renamed φ to phi).
-/
def HadamardInequalityStatement : Prop :=
  ∀ {n : ℕ} (M : Matrix (Fin n) (Fin n) ℂ),
    ‖M.det‖ ^ 2 ≤ ∏ i : Fin n, ∑ j : Fin n, ‖M i j‖ ^ 2

def PetalsStatement : Prop :=
  ∀ {n : ℕ} (P : Polynomial ℂ),
    P.Monic → P.natDegree = n →
    (∀ z ∈ P.roots, ‖z‖ ≤ 1) →
    (non_degenerate P →
      ∃ (components : Fin n → Set ℂ),
        (∀ i, IsOpen (components i)) ∧
        (∀ i, IsConnected (components i)) ∧
        (⋃ i, components i) = lemniscate P 1 ∧
        (∀ i j, i ≠ j → Disjoint (components i) (components j)) ∧
        (∀ i, ∃! z, z ∈ P.roots ∧ z ∈ components i)) ∧
    ((∃ (components : Fin n → Set ℂ),
        (∀ i, IsOpen (components i)) ∧
        (∀ i, IsConnected (components i)) ∧
        (⋃ i, components i) = lemniscate P 1 ∧
        (∀ i j, i ≠ j → Disjoint (components i) (components j)) ∧
        (∀ i, ∃! z, z ∈ P.roots ∧ z ∈ components i)) →
      non_degenerate P)

def ConformalFactorizationStatement : Prop :=
  ∀ {n : ℕ} (P : Polynomial ℂ) (z_star : ℂ) (k : ℕ),
    P.Monic → P.natDegree = n →
    (∀ z ∈ P.roots, ‖z‖ ≤ 1) →
    P.roots.Nodup →
    z_star ∈ P.roots →
    k ≥ 2 →
    ∃ (phi : ℂ → ℂ) (B : ℂ → ℂ),
      DifferentiableOn ℂ phi (Metric.ball 0 1) ∧
      Set.InjOn phi (Metric.ball 0 1) ∧
      phi 0 = z_star ∧
      (∀ w ∈ Metric.ball (0:ℂ) 1, B w = P.eval (phi w)) ∧
      B 0 = 0 ∧
      (∀ w ∈ Metric.ball (0:ℂ) 1, ‖B w‖ < 1) ∧
      DifferentiableOn ℂ B (Metric.ball 0 1) ∧
      deriv phi 0 = deriv B 0 / (Polynomial.derivative P).eval z_star

/-
Lemma: The squared norm of the Vandermonde determinant for points in the unit disk is bounded by n^n, using Hadamard's inequality.
-/
lemma vandermonde_det_bound_of_hadamard
    (h_hadamard : HadamardInequalityStatement)
    {n : ℕ} (z : Fin n → ℂ) (h_norm : ∀ i, ‖z i‖ ≤ 1) :
    ‖(Matrix.vandermonde z).det‖ ^ 2 ≤ (n : ℝ) ^ n := by
      -- Apply Hadamard's inequality to the Vandermonde matrix.
      have h_vandermonde_hadamard : ‖(Matrix.vandermonde z).det‖ ^ 2 ≤ ∏ i : Fin n, ∑ j : Fin n, ‖(z i) ^ (j : ℕ)‖ ^ 2 := by
        convert h_hadamard ( Matrix.vandermonde z ) using 1;
      refine le_trans h_vandermonde_hadamard ?_;
      refine' le_trans ( Finset.prod_le_prod _ fun i _ => Finset.sum_le_sum fun j _ => show ( ‖z i ^ ( j : ℕ )‖ ^ 2 : ℝ ) ≤ 1 ^ ( j : ℕ ) from _ ) _ <;> norm_num;
      · exact fun i => Finset.sum_nonneg fun _ _ => sq_nonneg _;
      · exact pow_le_one₀ ( norm_nonneg _ ) ( h_norm i )

/-
Proof of FeketeBoundStatement from HadamardInequalityStatement.
-/
theorem fekete_bound_of_hadamard (h_hadamard : HadamardInequalityStatement) : FeketeBoundStatement := by
  intro n z hz h_norm
  by_cases hn : n ≥ 2;
  · have := vandermonde_det_bound_of_hadamard h_hadamard z h_norm;
    -- Rewrite the determinant as product of differences.
    have h_det : ‖(Matrix.vandermonde z).det‖ = ∏ i : Fin n, ∏ j ∈ Finset.Ioi i, ‖z i - z j‖ := by
      rw [ Matrix.det_vandermonde ];
      norm_num [ norm_sub_rev, Finset.prod_mul_distrib ];
    -- Take the logarithm of both sides of the inequality.
    have h_log : Real.log (∏ i : Fin n, ∏ j ∈ Finset.Ioi i, ‖z i - z j‖) ≤ (n / 2 : ℝ) * Real.log n := by
      field_simp;
      convert Real.log_le_log ( ?_ ) this using 1 <;> norm_num [ h_det ];
      · ring;
      · exact sq_pos_of_pos <| h_det ▸ norm_pos_iff.mpr ( show Matrix.det ( Matrix.vandermonde z ) ≠ 0 from by rw [ Matrix.det_vandermonde ] ; exact Finset.prod_ne_zero_iff.mpr fun i hi => Finset.prod_ne_zero_iff.mpr fun j hj => sub_ne_zero_of_ne <| hz.ne <| by aesop );
    rw [ Real.log_prod ] at h_log;
    · convert h_log using 1;
      simp +decide [ Finset.sum_ite, Finset.filter_lt_eq_Ioi ];
      exact Finset.sum_congr rfl fun i hi => by rw [ Real.log_prod _ _ fun j hj => norm_ne_zero_iff.mpr <| sub_ne_zero.mpr <| hz.ne <| by aesop ] ;
    · exact fun i _ => Finset.prod_ne_zero_iff.mpr fun j hj => norm_ne_zero_iff.mpr <| sub_ne_zero.mpr <| hz.ne <| by aesop;
  · interval_cases n <;> norm_num

/-
Checking for Gauss-Lucas and convex hull theorems in Mathlib.
-/
#check Polynomial.rootSet_derivative_subset_convexHull_rootSet
#check convexHull_min
#check convex_closedBall

/-
Statement of the Dual Fekete Bound: For a monic polynomial P of degree n ≥ 2 with roots in the unit disk, there exists a critical point ζ (root of P') such that |P''(ζ)| ≤ n(n-1).
-/
def DualFeketeBoundStatement : Prop :=
  ∀ {n : ℕ} (P : Polynomial ℂ),
    P.Monic → P.natDegree = n →
    (∀ z ∈ P.roots, ‖z‖ ≤ 1) →
    n ≥ 2 →
    ∃ ζ, (derivative P).eval ζ = 0 ∧ ‖(derivative (derivative P)).eval ζ‖ ≤ n * (n - 1)

/-
Lemma: If P' = n * ∏(z - z_i), then P''(z_k) = n * ∏_{j ≠ k} (z_k - z_j).
-/
lemma second_deriv_at_critical_point {n : ℕ} (P : Polynomial ℂ)
    (hM : P.Monic) (hdeg : P.natDegree = n) (hn : n ≥ 2)
    (z : Fin (n - 1) → ℂ)
    (h_decomp : derivative P = C (n : ℂ) * ∏ i : Fin (n - 1), (X - C (z i)))
    (k : Fin (n - 1)) :
    (derivative (derivative P)).eval (z k) = (n : ℂ) * ∏ j : Fin (n - 1), if j = k then 1 else (z k - z j) := by
      simp +decide [ h_decomp, Polynomial.eval_prod, Finset.prod_ite, Finset.filter_ne' ];
      erw [ Finset.prod_eq_prod_diff_singleton_mul <| Finset.mem_univ k ];
      simp +decide [ Polynomial.eval_prod, Finset.sdiff_singleton_eq_erase ]

/-
Lemma: If a polynomial P has all roots in the unit disk, then its derivative P' also has all roots in the unit disk.
-/
lemma roots_derivative_in_disc {n : ℕ} (P : Polynomial ℂ)
    (h_deg : P.natDegree = n) (hn : n ≥ 2)
    (h_roots_disc : ∀ z ∈ P.roots, ‖z‖ ≤ 1) :
    ∀ z ∈ (derivative P).roots, ‖z‖ ≤ 1 := by
      -- By the Gauss-Lucas theorem, the roots of the derivative of a polynomial lie within the convex hull of the roots of the polynomial.
      have h_gauss_lucas : ∀ z ∈ Polynomial.roots (Polynomial.derivative P), z ∈ convexHull ℝ (Polynomial.roots P).toFinset := by
        have h_gauss_lucas : Polynomial.rootSet (Polynomial.derivative P) ℂ ⊆ convexHull ℝ (Polynomial.rootSet P ℂ) := by
          apply Polynomial.rootSet_derivative_subset_convexHull_rootSet;
          exact Polynomial.natDegree_pos_iff_degree_pos.mp ( by linarith );
        simp_all +decide [ Polynomial.rootSet_def ];
        simp_all +decide [ Set.subset_def, Polynomial.aroots_def ];
      intro z hz;
      specialize h_gauss_lucas z hz;
      rw [ mem_convexHull_iff ] at h_gauss_lucas;
      exact h_gauss_lucas ( Metric.closedBall 0 1 ) ( by aesop_cat ) ( convex_closedBall _ _ ) |> fun h => by simpa using h;

/-
Lemma: Dual Fekete Bound for the case where P' has distinct roots.
-/
lemma dual_fekete_bound_distinct_roots
    (h_hadamard : HadamardInequalityStatement)
    {n : ℕ} (P : Polynomial ℂ)
    (hM : P.Monic) (hdeg : P.natDegree = n) (hn : n ≥ 2)
    (h_roots_disc : ∀ z ∈ P.roots, ‖z‖ ≤ 1)
    (h_nodup : (derivative P).roots.Nodup) :
    ∃ ζ, (derivative P).eval ζ = 0 ∧ ‖(derivative (derivative P)).eval ζ‖ ≤ n * (n - 1) := by
      -- Let $\zeta_1, \ldots, \zeta_{n-1}$ be the roots of $P'$.
      obtain ⟨ζ, hζ⟩ : ∃ ζ : Fin (n - 1) → ℂ, (derivative P = Polynomial.C (n : ℂ) * Finset.prod Finset.univ (fun i => (Polynomial.X - Polynomial.C (ζ i)))) := by
        have h_roots_deriv : (derivative P).natDegree = n - 1 := by
          cases n <;> simp_all +decide [ Polynomial.natDegree_eq_of_degree_eq_some ];
        have h_roots_deriv : ∃ ζ : Fin (n - 1) → ℂ, (derivative P).roots = Multiset.ofList (List.ofFn ζ) := by
          have h_roots_deriv : Multiset.card (derivative P).roots = n - 1 := by
            have h_splits : Polynomial.Splits (algebraMap ℂ ℂ) (derivative P) := by
              exact?;
            erw [ Polynomial.splits_iff_card_roots ] at h_splits ; aesop;
          obtain ⟨ζ, hζ⟩ : ∃ ζ : List ℂ, (derivative P).roots = Multiset.ofList ζ ∧ ζ.length = n - 1 := by
            exact ⟨ Multiset.toList ( Polynomial.roots ( derivative P ) ), by simpa, by simpa using h_roots_deriv ⟩;
          use fun i => ζ.get! i;
          convert hζ.1 using 2;
          refine' List.ext_get _ _ <;> aesop;
        obtain ⟨ζ, hζ⟩ := h_roots_deriv
        have h_factor_deriv : derivative P = Polynomial.C (n : ℂ) * Multiset.prod (Multiset.map (fun z => Polynomial.X - Polynomial.C z) (Polynomial.roots (derivative P))) := by
          convert Polynomial.eq_prod_roots_of_splits_id _ using 1;
          · rcases n with ( _ | _ | n ) <;> simp_all +decide [ Polynomial.leadingCoeff, Polynomial.natDegree ];
            simp_all +decide [ Polynomial.coeff_derivative, Polynomial.Monic.def, Polynomial.leadingCoeff, Polynomial.natDegree ];
          · exact?;
        use ζ; rw [h_factor_deriv, hζ]; simp [List.prod_ofFn];
      -- Apply the lemma second_deriv_at_critical_point to each root ζ_i.
      have h_second_deriv : ∀ i : Fin (n - 1), ‖(derivative (derivative P)).eval (ζ i)‖ = (n : ℝ) * ∏ j ∈ Finset.univ.erase i, ‖ζ i - ζ j‖ := by
        intro i
        have h_deriv : (derivative (derivative P)).eval (ζ i) = (n : ℂ) * ∏ j ∈ Finset.univ.erase i, (ζ i - ζ j) := by
          simp +decide [ hζ, Polynomial.eval_prod, Finset.prod_eq_prod_diff_singleton_mul ( Finset.mem_univ i ) ];
          exact Or.inl ( by rw [ Finset.sdiff_singleton_eq_erase ] )
        simp [h_deriv];
      -- By the properties of the Vandermonde determinant, we know that $\prod_{i < j} |\zeta_i - \zeta_j|^2 = |\det V|^2$, where $V$ is the Vandermonde matrix.
      have h_vandermonde : ∏ i : Fin (n - 1), ∏ j ∈ Finset.univ.erase i, ‖ζ i - ζ j‖ = ‖(Matrix.vandermonde ζ).det‖ ^ 2 := by
        have h_vandermonde : ‖(Matrix.vandermonde ζ).det‖ = ∏ i : Fin (n - 1), ∏ j ∈ Finset.Ioi i, ‖ζ i - ζ j‖ := by
          rw [ Matrix.det_vandermonde ];
          norm_num [ norm_sub_rev ];
        have h_vandermonde_sq : ∏ i : Fin (n - 1), ∏ j ∈ Finset.univ.erase i, ‖ζ i - ζ j‖ = (∏ i : Fin (n - 1), ∏ j ∈ Finset.Ioi i, ‖ζ i - ζ j‖) * (∏ i : Fin (n - 1), ∏ j ∈ Finset.Iio i, ‖ζ i - ζ j‖) := by
          rw [ ← Finset.prod_mul_distrib ];
          refine' Finset.prod_congr rfl fun i hi => _;
          rw [ ← Finset.prod_union ];
          · rcongr j ; aesop;
          · exact Finset.disjoint_left.mpr fun x hx₁ hx₂ => lt_asymm ( Finset.mem_Ioi.mp hx₁ ) ( Finset.mem_Iio.mp hx₂ );
        rw [ h_vandermonde_sq, h_vandermonde, sq ];
        simp +decide [ Finset.prod_sigma', Finset.prod_mul_distrib ];
        refine' Or.inl ( Finset.prod_bij ( fun x hx => ⟨ x.snd, x.fst ⟩ ) _ _ _ _ ) <;> simp +decide;
        · bound;
        · exact fun b hb => ⟨ b.snd, b.fst, hb, rfl ⟩;
        · exact fun _ _ => norm_sub_rev _ _;
      -- By the properties of the Vandermonde determinant, we know that $|\det V|^2 \leq (n-1)^{n-1}$.
      have h_vandermonde_bound : ‖(Matrix.vandermonde ζ).det‖ ^ 2 ≤ (n - 1 : ℝ) ^ (n - 1) := by
        have h_vandermonde_bound : ∀ i : Fin (n - 1), ‖ζ i‖ ≤ 1 := by
          intro i
          have h_root : ζ i ∈ (derivative P).roots := by
            simp_all +decide [ Polynomial.eval_prod, Finset.prod_eq_zero ( Finset.mem_univ i ) ];
            exact ⟨ by linarith, Finset.prod_ne_zero_iff.mpr fun i _ => Polynomial.X_sub_C_ne_zero _ ⟩;
          apply roots_derivative_in_disc P hdeg hn h_roots_disc; assumption;
        convert vandermonde_det_bound_of_hadamard h_hadamard ζ h_vandermonde_bound using 1 ; cases n <;> norm_num at *;
      -- By the properties of the product, we know that there exists some $i$ such that $\prod_{j \neq i} |\zeta_i - \zeta_j| \leq (n-1)$.
      obtain ⟨i, hi⟩ : ∃ i : Fin (n - 1), ∏ j ∈ Finset.univ.erase i, ‖ζ i - ζ j‖ ≤ (n - 1 : ℝ) := by
        contrapose! h_vandermonde_bound;
        rw [ ← h_vandermonde ];
        exact lt_of_le_of_lt ( by norm_num ) ( Finset.prod_lt_prod ( fun _ _ => by exact sub_pos.mpr ( Nat.one_lt_cast.mpr hn ) ) ( fun _ _ => by exact le_of_lt ( h_vandermonde_bound _ ) ) ( show ∃ i : Fin ( n - 1 ), i ∈ Finset.univ ∧ ( n - 1 : ℝ ) < ∏ j ∈ Finset.univ.erase i, ‖ζ i - ζ j‖ from ⟨ ⟨ 0, Nat.sub_pos_of_lt hn ⟩, Finset.mem_univ _, h_vandermonde_bound _ ⟩ ) );
      exact ⟨ ζ i, by rw [ hζ ] ; simp +decide [ Finset.prod_eq_prod_diff_singleton_mul ( Finset.mem_univ i ) ], by rw [ h_second_deriv i ] ; exact mul_le_mul_of_nonneg_left hi <| Nat.cast_nonneg _ ⟩

/-
Proof of Dual Fekete Bound.
1. Prove P' ≠ 0.
2. If P' has distinct roots, use `dual_fekete_bound_distinct_roots`.
3. If P' has a repeated root ζ, then count > 1.
4. This implies P'(ζ) = 0.
5. Also rootMultiplicity ζ P' > 1.
6. Prove P'' ≠ 0.
7. Using `rootMultiplicity_sub_one_le_derivative_rootMultiplicity`, rootMultiplicity ζ P'' ≥ 1.
8. Thus P''(ζ) = 0.
9. The bound 0 ≤ n(n-1) holds.
-/
theorem dual_fekete_bound
    (h_hadamard : HadamardInequalityStatement) : DualFeketeBoundStatement := by
      intro n P hM hdeg hn h_roots_disc
      by_cases h_nodup : (derivative P).roots.Nodup;
      · exact?;
      · -- If P' has a repeated root ζ, then count > 1.
        obtain ⟨ζ, hζ⟩ : ∃ ζ, (derivative P).eval ζ = 0 ∧ rootMultiplicity ζ (derivative P) > 1 := by
          rw [ Multiset.nodup_iff_count_le_one ] at h_nodup;
          norm_num +zetaDelta at *;
          exact h_nodup.imp fun x hx => ⟨ by contrapose! hx; simp_all +decide [ Polynomial.rootMultiplicity_eq_zero ], hx ⟩;
        -- Since ζ is a root of P' with multiplicity greater than 1, we have P''(ζ) = 0.
        have hζ'' : (derivative (derivative P)).eval ζ = 0 := by
          exact Polynomial.isRoot_iterate_derivative_of_lt_rootMultiplicity hζ.2;
        exact ⟨ ζ, hζ.1, by rw [ hζ'' ] ; norm_num; nlinarith [ show ( n : ℝ ) ≥ 2 by norm_cast ] ⟩

/-
Lemma 5.2: Second derivative chain rule at a critical point of the outer function.
Assumes phi is differentiable in a neighborhood of w_c.
-/
lemma lemma_5_2_chain_rule_second_deriv
    (P : Polynomial ℂ) (phi : ℂ → ℂ) (B : ℂ → ℂ) (w_c : ℂ)
    (h_diff_phi_nhds : ∀ᶠ w in 𝓝 w_c, DifferentiableAt ℂ phi w)
    (h_diff_phi' : DifferentiableAt ℂ (deriv phi) w_c)
    (h_comp : ∀ᶠ w in 𝓝 w_c, B w = P.eval (phi w))
    (h_crit_P : (derivative P).eval (phi w_c) = 0) :
    deriv (deriv B) w_c = (derivative (derivative P)).eval (phi w_c) * (deriv phi w_c) ^ 2 := by
      -- By definition of $B$, we know that its first derivative is given by the chain rule.
      have h_deriv_B : ∀ᶠ w in nhds w_c, deriv B w = deriv P.eval (phi w) * deriv phi w := by
        have h_deriv_B : ∀ᶠ w in nhds w_c, deriv B w = deriv (fun w => P.eval (phi w)) w := by
          rw [ Metric.eventually_nhds_iff ] at *;
          obtain ⟨ ε, ε_pos, hε ⟩ := h_comp; exact ⟨ ε, ε_pos, fun y hy => Filter.EventuallyEq.deriv_eq <| Filter.eventuallyEq_of_mem ( IsOpen.mem_nhds ( Metric.isOpen_ball ) hy ) fun z hz => hε hz ⟩ ;
        filter_upwards [ h_deriv_B, h_diff_phi_nhds ] with w hw hw';
        convert deriv_comp w ( show DifferentiableAt ℂ ( fun x => P.eval x ) ( phi w ) from ?_ ) hw' using 1;
        exact P.differentiableAt;
      rw [ Filter.EventuallyEq.deriv_eq h_deriv_B ] ; norm_num [ h_crit_P, h_diff_phi', sq, mul_assoc, mul_comm, mul_left_comm ] ; ring;
      convert HasDerivAt.deriv ( HasDerivAt.mul ( h_diff_phi'.hasDerivAt ) ( HasDerivAt.comp w_c ( Polynomial.hasDerivAt _ _ ) ( h_diff_phi_nhds.self_of_nhds |> DifferentiableAt.hasDerivAt ) ) ) using 1 ; ring!; aesop;

/-
Corollary 5.3: Relation between the second derivative of the Blaschke product and the polynomial at a critical point.
-/
lemma corollary_5_3
    (P : Polynomial ℂ) (phi : ℂ → ℂ) (B : ℂ → ℂ) (w_c : ℂ)
    (h_diff_phi_nhds : ∀ᶠ w in 𝓝 w_c, DifferentiableAt ℂ phi w)
    (h_diff_phi' : DifferentiableAt ℂ (deriv phi) w_c)
    (h_comp : ∀ᶠ w in 𝓝 w_c, B w = P.eval (phi w))
    (h_crit_P : (derivative P).eval (phi w_c) = 0)
    (h_P''_ne_zero : (derivative (derivative P)).eval (phi w_c) ≠ 0) :
    ‖deriv phi w_c‖ ^ 2 = ‖deriv (deriv B) w_c‖ / ‖(derivative (derivative P)).eval (phi w_c)‖ := by
      -- Apply Lemma 5.2 to get B''(w_c) = P''(phi(w_c)) * (phi'(w_c))^2.
      have h_chain : deriv (deriv B) w_c = (derivative (derivative P)).eval (phi w_c) * (deriv phi w_c) ^ 2 := by
        apply_rules [ lemma_5_2_chain_rule_second_deriv ];
      rw [ h_chain, norm_mul, norm_pow ] ; aesop

/-
Checking for polynomial derivative identity and splits property.
-/
#check Polynomial.eval_derivative_div_eval_of_ne_zero_of_splits
#check IsAlgClosed.splits_codomain

/-
Identity for the second derivative of a polynomial at a critical point that is not a root.
-/
lemma polynomial_second_deriv_identity (P : Polynomial ℂ) (ζ : ℂ)
    (hM : P.Monic)
    (h_crit : (derivative P).eval ζ = 0)
    (h_not_root : P.eval ζ ≠ 0) :
    (derivative (derivative P)).eval ζ = - P.eval ζ * (P.roots.map (fun z => 1 / (ζ - z) ^ 2)).sum := by
      -- By definition of polynomial multiplication and the properties of roots, we can express P as a product of its roots.
      have hP_factor : P = Multiset.prod (Multiset.map (fun z => Polynomial.X - Polynomial.C z) P.roots) := by
        convert Polynomial.eq_prod_roots_of_monic_of_splits_id hM _;
        exact?;
      -- Using the fact that the logarithmic derivative is the sum of the reciprocals of the differences between the roots and any point, we can express the second derivative.
      have h_log_deriv : ∀ (m : Multiset ℂ), (∀ z ∈ m, ζ ≠ z) → (Polynomial.derivative (Multiset.prod (Multiset.map (fun z => Polynomial.X - Polynomial.C z) m))).eval ζ = (Multiset.prod (Multiset.map (fun z => ζ - z) m)) * (Multiset.sum (Multiset.map (fun z => (ζ - z)⁻¹) m)) := by
        intro m hm; induction m using Multiset.induction <;> norm_num at *;
        rename_i k hk; rw [ hk hm.2 ] ; simp +decide [ mul_add, mul_assoc, mul_comm, mul_left_comm, sub_ne_zero, hm.1 ] ; ring;
        simp +decide [ Polynomial.eval_multiset_prod ];
      -- Using the fact that the logarithmic derivative is the sum of the reciprocals of the differences between the roots and any point, we can express the second derivative as follows:
      have h_second_deriv : (Polynomial.derivative (Polynomial.derivative (Multiset.prod (Multiset.map (fun z => Polynomial.X - Polynomial.C z) P.roots)))).eval ζ =
        (Multiset.prod (Multiset.map (fun z => ζ - z) P.roots)) *
        ((Multiset.sum (Multiset.map (fun z => (ζ - z)⁻¹) P.roots)) ^ 2 -
        (Multiset.sum (Multiset.map (fun z => (ζ - z)⁻¹ ^ 2) P.roots))) := by
          have h_second_deriv : ∀ (m : Multiset ℂ), (∀ z ∈ m, ζ ≠ z) → (Polynomial.derivative (Polynomial.derivative (Multiset.prod (Multiset.map (fun z => Polynomial.X - Polynomial.C z) m)))).eval ζ =
            (Multiset.prod (Multiset.map (fun z => ζ - z) m)) *
            ((Multiset.sum (Multiset.map (fun z => (ζ - z)⁻¹) m)) ^ 2 -
            (Multiset.sum (Multiset.map (fun z => (ζ - z)⁻¹ ^ 2) m))) := by
              intro m hm; induction' m using Multiset.induction with z m ih <;> norm_num at *;
              rw [ h_log_deriv m hm.2, ih hm.2 ] ; ring;
              grind;
          exact h_second_deriv _ fun z hz => by rintro rfl; exact h_not_root <| by simpa using Polynomial.isRoot_of_mem_roots hz;
      rw [ hP_factor, h_second_deriv ];
      norm_num [ Polynomial.eval_multiset_prod ] at *;
      have h_log_deriv_zero : (Multiset.prod (Multiset.map (fun z => ζ - z) P.roots)) * (Multiset.sum (Multiset.map (fun z => (ζ - z)⁻¹) P.roots)) = 0 := by
        rw [ ← h_log_deriv _ fun z hz => by rintro rfl; exact h_not_root <| by simpa using Polynomial.isRoot_of_mem_roots hz ] ; rw [ ← hP_factor ] ; simp +decide [ h_crit ] ;
      linear_combination' h_log_deriv_zero * Multiset.sum ( Multiset.map ( fun z => ( ζ - z ) ⁻¹ ) P.roots )

/-
Identity for the second derivative of the Blaschke product of degree 2 at a critical point.
-/
def blaschke_k2 (β : ℂ) (w : ℂ) : ℂ := w * (w - β) / (1 - star β * w)

theorem blaschke_k2_identity (β : ℂ) (w_c : ℂ)
    (hβ : ‖β‖ < 1) (hw_c : ‖w_c‖ < 1)
    (h_crit : deriv (blaschke_k2 β) w_c = 0) :
    ‖deriv (deriv (blaschke_k2 β)) w_c‖ * (1 - ‖w_c‖ ^ 2) ^ 2 = 2 * (1 - ‖blaschke_k2 β w_c‖ ^ 2) := by
      -- Compute the first derivative of the Blaschke product.
      have h_deriv : deriv (blaschke_k2 β) = fun w => (2 * w - β - starRingEnd ℂ β * w ^ 2) / (1 - starRingEnd ℂ β * w) ^ 2 := by
        funext w;
        by_cases hw : 1 - starRingEnd ℂ β * w = 0 <;> simp_all +decide [ div_eq_mul_inv ];
        · rw [ deriv_zero_of_not_differentiableAt ];
          intro h_diff
          have h_lim : Filter.Tendsto (fun z => ‖blaschke_k2 β z‖) (nhdsWithin w {w}ᶜ) Filter.atTop := by
            have h_lim : Filter.Tendsto (fun z => ‖1 - starRingEnd ℂ β * z‖⁻¹) (nhdsWithin w {w}ᶜ) Filter.atTop := by
              refine' Filter.Tendsto.inv_tendsto_nhdsGT_zero _;
              refine' tendsto_nhdsWithin_iff.mpr _;
              refine' ⟨ _, _ ⟩;
              · exact tendsto_nhdsWithin_of_tendsto_nhds ( Continuous.tendsto' ( by continuity ) _ _ ( by aesop ) );
              · rw [ eventually_nhdsWithin_iff ];
                rw [ Metric.eventually_nhds_iff ];
                refine' ⟨ 1 / ( ‖starRingEnd ℂ β‖ + 1 ), by positivity, fun y hy hy' => _ ⟩ ; simp_all +decide [ sub_eq_iff_eq_add ];
                exact ⟨ Ne.symm hy', by rintro rfl; norm_num at hw ⟩;
            have h_lim : Filter.Tendsto (fun z => ‖z * (z - β)‖ * ‖1 - starRingEnd ℂ β * z‖⁻¹) (nhdsWithin w {w}ᶜ) Filter.atTop := by
              apply Filter.Tendsto.pos_mul_atTop;
              rotate_right;
              exact ‖w * ( w - β )‖;
              · simp_all +decide [ sub_eq_iff_eq_add ];
                refine' mul_pos ( norm_pos_iff.mpr _ ) ( norm_pos_iff.mpr _ ) <;> intro h <;> simp_all +decide [ Complex.ext_iff ];
                norm_num [ show w.re = β.re by linarith, show w.im = β.im by linarith ] at *;
                norm_num [ Complex.normSq, Complex.norm_def ] at * ; nlinarith [ Real.sqrt_nonneg ( β.re * β.re + β.im * β.im ), Real.mul_self_sqrt ( add_nonneg ( mul_self_nonneg β.re ) ( mul_self_nonneg β.im ) ) ];
              · exact Continuous.continuousWithinAt ( by continuity );
              · convert h_lim using 1;
            convert h_lim using 2 ; norm_num [ blaschke_k2 ];
            ring;
          exact not_tendsto_atTop_of_tendsto_nhds ( h_diff.continuousAt.norm.continuousWithinAt ) h_lim;
        · convert HasDerivAt.deriv ( HasDerivAt.div ( HasDerivAt.mul ( hasDerivAt_id' w ) ( HasDerivAt.sub ( hasDerivAt_id' w ) ( hasDerivAt_const _ _ ) ) ) ( HasDerivAt.sub ( hasDerivAt_const _ _ ) ( HasDerivAt.mul ( hasDerivAt_const _ _ ) ( hasDerivAt_id' w ) ) ) hw ) using 1 ; norm_num ; ring;
      by_cases h : 1 - starRingEnd ℂ β * w_c = 0 <;> simp_all +decide [ mul_comm ];
      · rw [ sub_eq_zero ] at h;
        replace h := congr_arg Norm.norm h ; norm_num at h ; nlinarith [ norm_nonneg β, norm_nonneg w_c ];
      · erw [ deriv_div ] <;> norm_num [ h, mul_comm ];
        unfold blaschke_k2; norm_num [ h, h_crit ] ; ring;
        field_simp;
        norm_num [ Complex.normSq, Complex.norm_def ] at *;
        rw [ Real.sq_sqrt ( by nlinarith ), Real.sq_sqrt ( by nlinarith ), Real.sq_sqrt ( by nlinarith ) ] ; ring;
        rw [ Real.sqrt_lt' ] at * <;> norm_num [ Complex.ext_iff, sq ] at *;
        field_simp;
        rw [ ← sq_eq_sq₀ ] <;> ring <;> try nlinarith;
        · rw [ Real.sq_sqrt ] <;> try nlinarith;
          · grind +ring;
          · nlinarith [ sq_nonneg ( w_c.re - β.re ), sq_nonneg ( w_c.im - β.im ) ];
        · field_simp;
          exact mul_nonneg ( Real.sqrt_nonneg _ ) ( by nlinarith [ sq_nonneg ( w_c.re ^ 2 + w_c.im ^ 2 - 1 ) ] );
        · nlinarith [ sq_nonneg ( w_c.re - β.re ), sq_nonneg ( w_c.im - β.im ), mul_self_nonneg ( w_c.re * β.im - w_c.im * β.re ) ]

/-
Checking if blaschke_k2 is defined and what it is.
-/
#check blaschke_k2
#print blaschke_k2

/-
Checking existence of lemma 5.2 and Blaschke identity.
-/
#check lemma_5_2_chain_rule_second_deriv
#check blaschke_k2_identity

/-
Theorem: The inradius of the lemniscate is bounded below by |B'(0)|/(4n) using the conformal factorization and Koebe theorem.
-/
theorem conformal_factorization_inradius_bound
    (P : Polynomial ℂ) (z_star : ℂ) (n : ℕ)
    (h_deg : P.natDegree = n)
    (h_root : z_star ∈ P.roots)
    (h_deriv_le : ‖(derivative P).eval z_star‖ ≤ n)
    (h_deriv_ne : (derivative P).eval z_star ≠ 0)
    (phi : ℂ → ℂ) (B : ℂ → ℂ)
    (h_diff_phi : DifferentiableOn ℂ phi (Metric.ball 0 1))
    (h_inj_phi : Set.InjOn phi (Metric.ball 0 1))
    (h_phi0 : phi 0 = z_star)
    (h_comp : ∀ w ∈ Metric.ball 0 1, B w = P.eval (phi w))
    (h_B_bound : ∀ w ∈ Metric.ball 0 1, ‖B w‖ < 1)
    (h_deriv_phi0 : deriv phi 0 = deriv B 0 / (derivative P).eval z_star)
    (h_koebe : KoebeQuarterStatement) :
    inradius (lemniscate P 1) ≥ ‖deriv B 0‖ / (4 * n) := by
      -- By the KoebeQuarterStatement, there exists a radius $r$ such that the ball of radius $r$ centered at $\phi(0)$ is contained in $\phi(\text{Metric.ball } 0 1)$.
      have h_ball : ∀ r, 0 < r → r < ‖deriv phi 0‖ / 4 → Metric.ball (phi 0) r ⊆ lemniscate P 1 := by
        intros r hr_pos hr_lt
        have h_ball_subset : Metric.ball (phi 0) r ⊆ phi '' (Metric.ball 0 1) := by
          have := h_koebe phi (phi 0) (deriv phi 0) ?_ ?_ ?_ ?_ ?_ <;> simp_all +decide [ Set.subset_def ];
          · exact fun x hx => this x <| lt_of_lt_of_le hx hr_lt.le;
          · intro h; norm_num [ h ] at hr_lt; linarith;
        generalize_proofs at *; (
        intro w hw; specialize h_ball_subset hw; aesop;)
      generalize_proofs at *; (
      -- Since $|deriv phi 0| = |deriv B 0| / |P'(z_star)|$ and $|P'(z_star)| \leq n$, we have $|deriv phi 0| \geq |deriv B 0| / n$.
      have h_deriv_phi0_bound : ‖deriv phi 0‖ ≥ ‖deriv B 0‖ / n := by
        rw [ h_deriv_phi0, norm_div ] ; gcongr;
      generalize_proofs at *; (
      -- Since the inradius is the supremum of the radii of balls contained in the lemniscate, and we have that for any r < ‖deriv B 0‖ / (4n), the ball of radius r is contained in the lemniscate, it follows that the inradius must be at least ‖deriv B 0‖ / (4n).
      have h_inradius_ge : ∀ r, 0 < r → r < ‖deriv B 0‖ / (4 * n) → r ≤ inradius (lemniscate P 1) := by
        intros r hr hr';
        refine' le_csSup _ _ <;> norm_num
        generalize_proofs at *; (
        -- Since the lemniscate is bounded, there exists some M such that for all z in the lemniscate, ‖z‖ ≤ M.
        obtain ⟨M, hM⟩ : ∃ M, ∀ z ∈ lemniscate P 1, ‖z‖ ≤ M := by
          have h_bounded : ∃ M, ∀ z, ‖P.eval z‖ < 1 → ‖z‖ ≤ M := by
            have h_poly_growth : Filter.Tendsto (fun z : ℂ => ‖P.eval z‖) (Filter.cocompact ℂ) Filter.atTop := by
              apply_rules [ Polynomial.tendsto_norm_atTop ];
              · exact not_le.mp fun h => by rw [ Polynomial.eq_C_of_degree_le_zero h ] at h_root h_deriv_ne; aesop;
              · exact tendsto_norm_cocompact_atTop
            have := h_poly_growth.eventually_gt_atTop 1
            generalize_proofs at *; (
            rw [ Filter.eventually_iff ] at this; simp_all +decide [ Filter.mem_cocompact ] ; (
            obtain ⟨ t, ht₁, ht₂ ⟩ := this; rcases ht₁.isBounded.exists_norm_le with ⟨ M, hM ⟩ ; exact ⟨ M, fun z hz => hM z <| by_contra fun hz' => not_lt_of_ge ( ht₂ ( by simpa using hz' ) |> le_of_lt ) hz ⟩ ;))
          generalize_proofs at *; (
          exact h_bounded.imp fun M hM z hz => hM z hz)
        generalize_proofs at *; (
        use M + M + 1; intro r hr; rcases hr with ⟨ hr₀, z, hz ⟩ ; have := hM z ( hz ( Metric.mem_ball_self hr₀ ) ) ; norm_num at *; (
        have := hM ( z + r / 2 ) ( hz <| Metric.mem_ball.mpr <| by simpa [ abs_of_pos hr₀ ] ) ; ( have := hM ( z - r / 2 ) ( hz <| Metric.mem_ball.mpr <| by simpa [ abs_of_pos hr₀ ] ) ; ( norm_num [ Complex.normSq, Complex.norm_def ] at *; ) );
        rw [ Real.sqrt_le_iff ] at * ; nlinarith [ sq_nonneg ( z.re - r / 2 ), sq_nonneg ( z.re + r / 2 ) ] ;);));
        exact ⟨ hr, phi 0, h_ball r hr ( by ring_nf at *; linarith ) ⟩
      generalize_proofs at *; (
      contrapose! h_inradius_ge;
      by_cases h : 0 < ‖deriv B 0‖ / ( 4 * n ) <;> simp_all +decide [ div_eq_mul_inv ];
      · exact ⟨ ( inradius ( lemniscate P 1 ) + ‖deriv B 0‖ * ( ( n : ℝ ) ⁻¹ * 4⁻¹ ) ) / 2, by linarith [ show 0 ≤ inradius ( lemniscate P 1 ) from by apply_rules [ Real.sSup_nonneg ] ; rintro r ⟨ hr₀, z, hz ⟩ ; exact hr₀.le ], by linarith, by linarith ⟩;
      · exact False.elim <| h.not_lt <| mul_pos ( norm_pos_iff.mpr <| show deriv B 0 ≠ 0 from fun h' => by norm_num [ h' ] at *; linarith [ show 0 ≤ inradius ( lemniscate P 1 ) from by apply_rules [ Real.sSup_nonneg ] ; rintro r ⟨ hr, z, hz ⟩ ; positivity ] ) <| mul_pos ( inv_pos.mpr <| Nat.cast_pos.mpr <| Nat.pos_of_ne_zero <| by aesop_cat ) <| by norm_num;)))
